# Generated by Django 3.0.5 on 2020-09-02 05:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
        CREATE SCHEMA content;
        GRANT ALL ON SCHEMA content TO admin;
        """)
    ]
