# Generated by Django 3.0.5 on 2020-05-02 23:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_id', models.UUIDField(null=True)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(max_length=256, null=True)),
                ('nationality', models.CharField(max_length=256, null=True)),
                ('bio', models.TextField(null=True)),
                ('external_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('JAZZ', 'Jazz'), ('ROCK', 'Rock'), ('BAROQUE', 'Baroque')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_one', models.CharField(max_length=256, null=True)),
                ('address_two', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=24, null=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=24, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('PRIMARY', 'Primary Artist'), ('FEATURED', 'Featured Artist'), ('WRITER', 'Writer'), ('PRODUCER', 'Producer'), ('COMPOSER', 'Composer'), ('SINGER', 'Singer'), ('PIANIST', 'Pianist'), ('KEYBOARDIST', 'Keyboardist'), ('DRUMMER', 'Drummer'), ('LAGERPHONIST', 'Lagerphonist'), ('LYRICIST', 'Lyricist'), ('PUBLICIST', 'Publicist'), ('STYLIST', 'Stylist'), ('KEY_GRIP', 'Key Grip'), ('MANAGER', 'Manager'), ('CONCEPTUALIST', 'Conceptualist'), ('GUITARIST', 'Guitarist'), ('SYNTHESIST', 'Synthesist')], default='PRIMARY', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SoundRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrate', models.IntegerField()),
                ('samplerate', models.IntegerField()),
                ('filetype', models.CharField(max_length=12)),
                ('length', models.IntegerField()),
                ('size', models.IntegerField()),
                ('channels', models.IntegerField()),
                ('file_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isrc', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=256)),
                ('purchase_cost', models.DecimalField(decimal_places=4, max_digits=6)),
                ('stream_cost', models.DecimalField(decimal_places=4, max_digits=6)),
                ('purchase_count', models.BigIntegerField(default=0)),
                ('stream_count', models.BigIntegerField(default=0)),
                ('notes', models.TextField()),
                ('artwork_id', models.UUIDField()),
                ('contributors', models.ManyToManyField(to='content.Contributor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.User')),
                ('sound_recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.SoundRecording')),
            ],
        ),
        migrations.CreateModel(
            name='RightsAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_name', models.TextField()),
                ('agreement_date', models.DateField()),
                ('owner', models.ManyToManyField(to='content.User')),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Role'),
        ),
        migrations.AddField(
            model_name='artist',
            name='birth_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_location', to='content.Location'),
        ),
        migrations.AddField(
            model_name='artist',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_location', to='content.Location'),
        ),
        migrations.AddField(
            model_name='artist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.User'),
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('default', models.BooleanField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('release_date', models.DateField()),
                ('upload_date', models.DateField()),
                ('remaster_date', models.DateField(null=True)),
                ('start_datetime', models.DateField()),
                ('artwork_id', models.UUIDField()),
                ('purchase_cost', models.DecimalField(decimal_places=4, max_digits=6)),
                ('purchase_count', models.BigIntegerField(default=0)),
                ('label_name', models.CharField(max_length=256, null=True)),
                ('notes', models.TextField(null=True)),
                ('artists', models.ManyToManyField(to='content.Contributor')),
                ('genres', models.ManyToManyField(to='content.Genre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.User')),
                ('recording_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Location')),
                ('tracks', models.ManyToManyField(to='content.Track')),
            ],
        ),
    ]
