# Generated by Django 3.0.5 on 2020-05-12 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iswc', models.CharField(max_length=24)),
                ('title', models.CharField(max_length=256)),
                ('notes', models.TextField()),
            ],
            options={
                'db_table': 'content"."composition',
            },
        ),
        migrations.CreateModel(
            name='CompositionContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Composition')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Contributor')),
            ],
            options={
                'db_table': 'content"."composition_contributor',
            },
        ),
        migrations.AddField(
            model_name='composition',
            name='contributors',
            field=models.ManyToManyField(through='content.CompositionContributor', to='content.Contributor'),
        ),
        migrations.AddField(
            model_name='composition',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.User'),
        ),
        migrations.AddField(
            model_name='track',
            name='composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Composition'),
        ),
    ]
