# Generated by Django 3.0.5 on 2020-05-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200512_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='rights_agreement',
        ),
        migrations.DeleteModel(
            name='RightsAgreement',
        ),
    ]
