# Generated by Django 3.0.5 on 2020-09-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200902_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artwork_id',
        ),
    ]
