# Generated by Django 3.0.5 on 2020-09-02 06:08

from django.db import migrations

PRIMARY = "PRIMARY"
FEATURED = "FEATURED"
WRITER = "WRITER"
PRODUCER = "PRODUCER"
COMPOSER = "COMPOSER"
SINGER = "SINGER"
PIANIST = "PIANIST"
KEYBOARDIST = "KEYBOARDIST"
DRUMMER = "DRUMMER"
LAGERPHONIST = "LAGERPHONIST"
LYRICIST = "LYRICIST"
PUBLICIST = "PUBLICIST"
STYLIST = "STYLIST"
KEY_GRIP = "KEY_GRIP"
MANAGER = "MANAGER"
CONCEPTUALIST = "CONCEPTUALIST"
GUITARIST = "GUITARIST"
SYNTHESIST = "SYNTHESIST"

CHOICES = [
    PRIMARY,
    FEATURED,
    WRITER,
    PRODUCER,
    COMPOSER,
    SINGER,
    PIANIST,
    KEYBOARDIST,
    DRUMMER,
    LAGERPHONIST,
    LYRICIST,
    PUBLICIST,
    STYLIST,
    KEY_GRIP,
    MANAGER,
    CONCEPTUALIST,
    GUITARIST,
    SYNTHESIST,
]

def forwards_func(apps, schema_editor):
    Role = apps.get_model("content", "Role")
    db_alias = schema_editor.connection.alias
    Role.objects.using(db_alias).bulk_create([
        Role(description=CHOICE)
        for CHOICE in CHOICES
    ])

def reverse_func(apps, schema_editor):
    Role = apps.get_model("content", "Role")
    db_alias = schema_editor.connection.alias
    Role.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_track_artwork_id'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
