# Generated by Django 3.0.5 on 2020-09-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_initial_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artwork_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='start_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='stream_cost',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
