# Generated by Django 3.0.5 on 2020-10-26 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20201026_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
