name: Deploy to production

on:
  push:
    branches: [ master ]

env:
  image_tag: waylostreams/catalog:${{ github.sha }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Black Check
      uses: waylostreamers/action-black@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.image_tag }}
    - name: Run tests
      run: ci/test
      env:
        IMAGE_TAG: ${{ env.image_tag }}
    - name: Push to docker hub
      run: ci/push
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        IMAGE_TAG: ${{ env.image_tag }}

  deploy:
    name: 'Deploy updated container image via blue/green deployment to ECS service.'
    needs: build-test-push
    runs-on: ubuntu-18.04
    steps:
    - name: Deploy
      uses: silinternational/ecs-deploy@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-1'
      with:
        aws_access_key_cmd: '--aws-access-key'
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key_cmd: '--aws-secret-key'
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        cluster_cmd: '--cluster'
        cluster: 'waylostreams-prod'
        image_cmd: '--image'
        image: registry.hub.docker.com/${{ env.image_tag }}
        region_cmd: '--region'
        region: 'us-west-1'
        service_name_cmd: '--service-name'
        service_name: 'django'
        timeout_cmd: '--timeout'
        timeout: '60'
