name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  image_tag: waylostreams/${{ github.repository }}_${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.image_tag }}
    - name: Run tests
      run: ci/test
      env:
        IMAGE_TAG: ${{ env.image_tag }}
    - name: Push to docker hub
      run: ci/push
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        IMAGE_TAG: ${{ env.image_tag }}
