name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  image_tag: ${{ github.repository }}_${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.image_tag }}
    - name: Start docker-compose stack
      run: IMAGE_TAG=${{ env.image_tag }} docker-compose -f ci/docker-compose.yml up -d
    - name: Test
      run: docker exec catalog_django_1 python manage.py test
