name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag waylostreams:$(date +%s)
    - name: Start docker-compose stack
      run: docker-compose -f docker-compose.yml up -d
    - name: Test
      run: docker exec catalog_django_1 python manage.py test
